name: Update RSS Feed

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight UTC
  workflow_dispatch:     # allow manual runs

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run feed update script
        run: python update_feed.py

      - name: Commit changes
        run: |
          git config user.name "vukilis"
          git config user.email "vuk.lekic@vukilis.com"
          git add README.md
          git commit -m "README" || echo "No changes"
          git push
